package ec.edu.ups.Prueba;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:54:33.013-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "ArteSOAPService",
                  wsdlLocation = "http://localhost:8080/Prueba-P2/ArteSOAP?wsdl",
                  targetNamespace = "http://services.prueba.ups.edu.ec/")
public class ArteSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.prueba.ups.edu.ec/", "ArteSOAPService");
    public final static QName ArteSOAPPort = new QName("http://services.prueba.ups.edu.ec/", "ArteSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Prueba-P2/ArteSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArteSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Prueba-P2/ArteSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArteSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArteSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArteSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ArteSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ArteSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ArteSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ArteSOAP
     */
    @WebEndpoint(name = "ArteSOAPPort")
    public ArteSOAP getArteSOAPPort() {
        return super.getPort(ArteSOAPPort, ArteSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArteSOAP
     */
    @WebEndpoint(name = "ArteSOAPPort")
    public ArteSOAP getArteSOAPPort(WebServiceFeature... features) {
        return super.getPort(ArteSOAPPort, ArteSOAP.class, features);
    }

}
