
package ec.edu.ups.Prueba;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:54:32.957-05:00
 * Generated source version: 3.5.0
 *
 */
public final class ArteSOAP_ArteSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.prueba.ups.edu.ec/", "ArteSOAPService");

    private ArteSOAP_ArteSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ArteSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ArteSOAPService ss = new ArteSOAPService(wsdlURL, SERVICE_NAME);
        ArteSOAP port = ss.getArteSOAPPort();

        {
        System.out.println("Invoking getObras...");
        java.util.List<ec.edu.ups.Prueba.Arte> arte = port.getObras();
        System.out.println("getObras.result=" + arte);


        }
        
        
       {
        System.out.println("Invoking insertar...");
        ec.edu.ups.Prueba.Arte arte = null;
        java.lang.String _insertar__return = port.insertar(arte);
        System.out.println("insertar.result=" + arte);


        }

        System.exit(0);
        
    }



}
